# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
